version: 2.1

orbs:
  slack: circleci/slack@4.10.1

jobs:
  install:
    working_directory: ~/symeo-cli
    docker:
      - image: cimg/go:1.20.3
    steps:
      - checkout
      - restore_cache:
          key: go-mod-v4-{{ checksum "~/symeo-cli/go.sum" }}
      - run:
          name: Install dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "~/symeo-cli/go.sum" }}
          paths:
            - "/go/pkg/mod"
      - slack/notify:
          event: fail
          template: basic_fail_1
  test:
    working_directory: ~/symeo-cli
    docker:
      - image: cimg/go:1.20.3
    steps:
      - checkout
      - restore_cache:
          key: go-mod-v4-{{ checksum "~/symeo-cli/go.sum" }}
      - run:
          name: Test
          command: go test ./... -v
      - slack/notify:
          event: fail
          template: basic_fail_1
  publish:
    working_directory: ~/symeo-js
    docker:
      - image: cimg/go:1.20.3
    steps:
      - checkout
      - restore_cache:
          key: go-mod-v4-{{ checksum "~/symeo-cli/go.sum" }}
      - run:
          name: Install goreleaser
          command: curl -sfL https://goreleaser.com/static/run | bash
      - run:
          name: Export github token
          command: GITHUB_TOKEN="${GITHUB_PACKAGES_TOKEN}"
      - run:
          name: Publish
          command: goreleaser release
      - slack/notify:
          event: fail
          template: basic_fail_1

workflows:
  package:
    jobs:
      - install:
          context:
            - slack-notifications
      - test:
          requires:
            - install
          context:
            - slack-notifications
      - publish:
          requires:
            - test
          context:
            - slack-notifications
            - github-packages
          filters:
            branches:
              only:
                - main
